name: Find mounted file systems
on:
  workflow_dispatch:
#  Uncomment for scheduled trigger each day at midnight
#  schedule:
#    - cron: '0 0 * * *'

jobs:

  get-aad-token:
    uses: ./.github/workflows/get-aad-token.yaml
    secrets:
      SPN_ID: ${{ secrets.SPN_ID }}
      SPN_SECRET: ${{ secrets.SPN_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

  find-mount-points:
    runs-on: ubuntu-latest
    needs: get-aad-token
    steps:
      - uses: actions/checkout@v3
      - id: decrypt-token
        run: |
          AAD_TOKEN_DECRYPTED=$(gpg --decrypt --quiet --batch --passphrase "$PGP_PASSPHRASE" --output - <(echo "$AAD_TOKEN_ENCRYPTED" | base64 --decode))
          echo "::add-mask::$AAD_TOKEN_DECRYPTED"
          echo "AAD_TOKEN_DECRYPTED=$AAD_TOKEN_DECRYPTED" >> $GITHUB_OUTPUT
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          AAD_TOKEN_ENCRYPTED: ${{ needs.get-aad-token.outputs.AAD_TOKEN_ENCRYPTED }}
      - run: |
          $GITHUB_WORKSPACE/executables/find-dbfs-mount-points.sh
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ steps.decrypt-token.outputs.AAD_TOKEN_DECRYPTED }}
